### ISSUE TITLE
Q: React Demo

### ISSUE THREAD

**Issue by tsujp** [zeit/spr-landing#13]
Is there a React SPR demo floating around somewhere? Given this is the example repo for a Next.js version I figure it's the most appropriate place I've seen so far to make a query about the existence of a React one.

**Comment by ivan-kleshnin** [comment]
I've experimented with SPR recently. It does decrease the evaluation metrics on the backend! So it can reduce your expenses indeed. 

As for performance... it's not as good as I hoped. TTFB from Zeit CDN fluctuates heavily (they don't have many servers it seems). I got all numbers between 50ms and 1000ms and for the same app hosted on DGO I had stable 250-300ms TTFB.

**Comment by paulogdm** [comment]
@ivan-kleshnin Can you share your test methodology and deployment so we can replicate?

**Comment by rauchg** [comment]
@ivan-kleshnin we are very close to launching the solution that addresses the "cold hit" problems of SPRv1. Internally we call it SPRv2. Look forward to sharing it with you all soon!

**Comment by ijjk** [comment]
Hey folks! We have upgraded this repo to take advantage of incremental static site generation (iSSG). In short:

- There’s never a cold boot anymore when accessing the page
- The page gets incrementally re-built asynchronously
- Always fast & available

This is thanks to Next.js' new hooks for static site generation, [see the RFC here](https://github.com/zeit/next.js/issues/9524), where you can learn more about how this works.

I’m closing this issue for now as it’s no longer applicable. Feel free to ping me with any questions.
