### ISSUE TITLE
Image src starts with `image.js?...`

### ISSUE THREAD

**Issue by coodoo** [zeit/spr-landing#19]
Seemed all image sources coming from notion were in following format, wondering how do one handle it so that they can be correctly displayed?

```
/image.js?url=https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fd8974e34-1163-4e26-a053-6180ea554871%2Fbridge.jpg
```

**Comment by ijjk** [comment]
Hey folks! We have upgraded this repo to take advantage of incremental static site generation (iSSG). In short:

- There’s never a cold boot anymore when accessing the page
- The page gets incrementally re-built asynchronously
- Always fast & available

This is thanks to Next.js' new hooks for static site generation, [see the RFC here](https://github.com/zeit/next.js/issues/9524), where you can learn more about how this works.

I’m closing this issue for now as it’s no longer applicable. Feel free to ping me with any questions.
