### ISSUE TITLE
Usage with gatsby

### ISSUE THREAD

**Issue by elie222** [zeit/spr-landing#6]
I have a Gastby site deployed with `now`. Where should these lines be going: `res.setHeader("Cache-Control", "s-maxage=1, stale-while-revalidate");`?

Or can I only us this feature with NextJS?

https://github.com/zeit/spr-landing/blob/master/pages/index.js#L178-L181

**Comment by paulogdm** [comment]
## Answer

You should insert that tag in both a page or an API response. In fact, in anything that you want the behavior described below by the caching mechanism.
- Serve the content that you have.
- In the background, refresh this content based on the original one.

A break-down for each component:
- `s-maxage=1`:  For how much time content should be considered "fresh".
- `stale-while-revalidate`: If the content is not fresh, serve it anyways but execute a refresh. This will tell the CDN the content should be fetched again but the content is "stale while revalidating".

**Comment by juice49** [comment]
Is it possible to have a rebuild triggered when using this header with `@now/static-build`?

The intro post gave me the impression this could be done:

> In short, you can begin adding this header to any of your Now deployments, using whatever technology you like (Next.js, **Gatsby**, Node.js, Go, Rust...), without any rewrites or lock-in.

(https://zeit.co/blog/serverless-pre-rendering)

But it doesn't seem to work for me.

package.json:

```
{
  "name": "spr-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "now-build": "mkdir ./dist && date > ./dist/index.html"
  },
  "author": "Ash",
  "license": "ISC"
}
```

now.json:

```
{
  "version": 2,
  "builds": [
    {
      "src": "package.json",
      "use": "@now/static-build"
    }
  ],
  "routes": [
    {
      "src": "^/(.*).html",
      "headers": {
        "Cache-Control": "public, max-age=1, stale-while-revalidate"
        }
      }
  ]
}
```

The date never changes, so it seems the build is only triggered on initial deploy.

It's totally possible that I've misunderstood 🙂. But some clarification on how this feature works with static build would be great! Thanks.

**Comment by paulogdm** [comment]
It is not about the build, but data. How do you fetch and store data?
This tag introduces a way to serve data while refreshing on the background. Try to look at https://zeit.co/blog/serverless-pre-rendering#cache-control:stale-while-revalidate
