### ISSUE TITLE
`require("crypto")` inside getInitialProps?

### ISSUE THREAD

**Issue by PetrSnobelt** [zeit/spr-landing#7]
require wouldn't work in client-side, it should be probably in `if (res) {` block

**Comment by ivan-kleshnin** [comment]
+1 and `crypto` is HUGE.

**Comment by ijjk** [comment]
Hey folks! We have upgraded this repo to take advantage of incremental static site generation (iSSG). In short:

- There’s never a cold boot anymore when accessing the page
- The page gets incrementally re-built asynchronously
- Always fast & available

This is thanks to Next.js' new hooks for static site generation, [see the RFC here](https://github.com/zeit/next.js/issues/9524), where you can learn more about how this works.

I’m closing this issue for now as it’s no longer applicable. Feel free to ping me with any questions.
