### ISSUE TITLE
TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by dlp-dev-composant** [zeit/spr-landing#9]
```node - v``` ```v12.2.0```
```git clone https://github.com/zeit/spr-landing/```
```now dev```

![Image of Yaktocat](https://file-kzmhaesvam.now.sh/)

**Comment by parweb** [comment]
Why is it closed ?

**Comment by christennguyen** [comment]
Hi, I'm seeing this issue again using:
`node - v` `v12.6.0`
`git clone https://github.com/zeit/spr-landing/`
`now dev`

However, if I duplicate the public Notion page of My SPR landing and use the duplicated page's PAGE_ID, then I get this:
<img width="1283" alt="Screen Shot 2019-07-13 at 1 24 50 PM" src="https://user-images.githubusercontent.com/4268219/61176233-26f5ab80-a572-11e9-85b7-45e5e8c4ca5d.png">

It's just the bottom portion of the content and nothing else.
